name: 'My Signer'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '33 0 * * *'

jobs:
  tieba_sign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests lxml
      - name: 'Start Sign'
        env:
          YJ_COOKIE: ${{ secrets.YJ_COOKIE }}
        run: python yjsign.py
